apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapache-deployment
  labels:
    app: phpapache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: phpapache
  template:
    metadata:
      labels:
        app: phpapache
    spec:
      containers:
      - name: phpapache
        image: mvilla/phpapache:v1
        ports:
        - name: http
          containerPort: 80
